### ISSUE TITLE
Feature request: Report git revision

### ISSUE THREAD

**Issue by pipping** [jcbeaudoin/MKCL#10]
The MKCL version is currently only reported as 1.1.10, both when the REPL comes up and e.g. by `(lisp-implementation-version)`, even though the git master is currently somewhere between 1.1.9 and 1.1.10. I'm not aware of a way to extract the git revision from the MKCL executable. This means that
- caches are mixed
- it's not possible to reliably label logs that might show a problem one revision exhibited but another did not.

Would it be possible to include the git revision (potentially in `git describe` format?) into the version the way that e.g. SBCL does it (1.3.9 + 55 commits leading to revision 25088e3  gives me "1.3.9.55-25088e3")?

**Comment by jcbeaudoin** [comment]
I'll look into it.

**Comment by jcbeaudoin** [comment]
[commit fc50d00](https://github.com/jcbeaudoin/MKCL/commit/fc50d0038f2f1579fbb7c6ae930c1d111448346e) adds #'mkcl:git-describe-this-mkcl as discussed privately.

**Comment by pipping** [comment]
I've worked around the issue that I've mentioned as a comment to fc50d00 by calling `make -C src lsp/git_describe.lsp` prior to regular make. This way, compilation succeeds for me. Moreover, `(mkcl:git-describe-this-mkcl)` gives me *1.1.9.155-fc50d00* as expected (`git describe --tags` would give me *v1.1.9-155-gfc50d00*), so I'd say this is working. Thanks :)

**Comment by pipping** [comment]
The make issue is now indeed fixed, thanks!
