### ISSUE TITLE
CFFI too old?

### ISSUE THREAD

**Issue by pipping** [jcbeaudoin/MKCL#12]
I'm having trouble loading osicat via quicklisp. The error I get is

```
Unknown CFFI type: :STRUCT.
```

It seems this is a known issue with older versions of CFFI.

**Comment by jcbeaudoin** [comment]
On Fri, Sep 30, 2016 at 7:38 PM, Elias Pipping <notifications@github.com>
wrote:

> I'm having trouble loading osicat via quicklisp. The error I get is
>
> Unknown CFFI type: :STRUCT.
>
> It seems this is a known issue with older versions of CFFI.
>
>
> It is more than likely to be the case indeed.
The bundled CFFI  is version 0.10.7.1 seems to date back
to about February 2014 at the latest.

It should definitely be updated before the next release of MKCL.

**Comment by jcbeaudoin** [comment]
With commit 2bc5964c11257a8443da4d737625230e3e01fe7b bundled CFFI package has now been upgraded to 0.18.0 (current release).

**Comment by jcbeaudoin** [comment]
CL+J 0.4, to be released soon, is now as functional on CFFI 0.18.0 as CL+J 0.3 used to be on the previous bundled version of CFFI. CL+J is a pretty extensive workout of CFFI therefore I consider this new version of  bundled CFFI to be good enough for general service. We'll simply have live with it from now on.
