### ISSUE TITLE
cffi-sys:%foreign-funcall doesn't pass the calling convention to si:call-cfun

### ISSUE THREAD

**Issue by davidmullen** [jcbeaudoin/MKCL#26]
Technically an issue with CFFI, but it's in the `contrib` directory.

For [cffi:foreign-funcall](https://cffi.common-lisp.dev/manual/html_node/foreign_002dfuncall.html) the default calling convention is `:cdecl`.

```
(require :asdf)
(require :cffi)
```

Then: 

```
> (cffi:foreign-funcall "strlen" :string "foo" :int)

Debugger called in: #<thread "Initial" active (10204) 0x7f2cccf3c740 7f2cca4f1000>.

#<a SIMPLE-ERROR 139829904682848>:
    NIL does no denote a valid calling convention.
```

For [mk_si_call_cfun](https://github.com/jcbeaudoin/MKCL/blob/8c31130ead2640c3a82b9fa86dffec0748a392e9/src/c/ffi.c#L777-L778) the default calling convention is `nil`.

This function, `si:call-cfun`, is called from [cffi-mkcl.lisp](https://github.com/cffi/cffi/blob/master/src/cffi-mkcl.lisp).

**Comment by jcbeaudoin** [comment]
I goofed during a massive commit a while back.  I did not transform properly the default value of two &optional arguments in src/c/ffi.c.  I will commit the fix some time tonight.  My sincere apologies for the inconvenience.

**Comment by jcbeaudoin** [comment]
commit e6d1df0 on master/head should be the needed fix. Please try.
