### ISSUE TITLE
Negative fixnum overflow in mkcl_ash

### ISSUE THREAD

**Issue by davidmullen** [jcbeaudoin/MKCL#31]
```
> (ash (1- most-negative-fixnum) 1)

-4611686018427387906
```

Which is fine—but then:

```
> (ash most-negative-fixnum 1)

0
```

**Comment by jcbeaudoin** [comment]
The code in `mkcl_ash()` seems to be ignoring the sign bit of the shifted original value.

**Comment by jcbeaudoin** [comment]
I think I have a fix.  I'll commit it later today after I twiddle it a bit more.

**Comment by jcbeaudoin** [comment]
Could you please try commit 9f2296c on master/head to see if it fixes the issue.

**Comment by davidmullen** [comment]
I ran a bunch of randomized tests (both compiled and interpreted) and everything looks OK.
