### ISSUE TITLE
Building MKCL on FreeBSD - threads.d - "error: unknown type name 'MK_GC_finalizer_notifier_proc'; did you mean 'GC_finalizer_notifier_proc'?"

### ISSUE THREAD

**Issue by spchamp** [jcbeaudoin/MKCL#6]
Hello,

Observing the support for MKCL in CL+J, and having taking up an interest about applying SWIG for C++ FFI in Common Lisp - specifically with LLVM on FreeBSD - moreover, towards ensuring a broader support for Common Lisp on FreeBSD, I've begun tinkering with developing a port for MKCL to FreeBSD. I've attached a preliminary diff of what I've been able to hack out for the port, so far. 

I believe that my patch may need some cleanups -- for instance, I would like to make sure I've not missed any `__linux` declarations in the source tree, such that could be accompanied with `defined(BSD)` compatibly. Furthermore, I'm not altogether certain if the patched source tree may be compatible with the project's style guidelines. In all candor, I've not been  a lot of comfortable with C or C++ but I understand that there may a manner of a normative language model to each, in any respective edition of the C or C++ languages. 

Concerning the following patch, it does not go to  much further of a semantic depth than preprocessor directives.

Presently, I'm hoping that there may be any advice available as to how to address the following errors form the compiler. 

This is produced with the LLVM toolchain, more specifically the clang C compiler and the LLVM C++ compiler, on FreeBSD 10.3 amd64. I've attached a transcript of the entire build session, along with the patch.

If it may be possible to build MKCL successfully on FreeBSD, I believe that there may be a good time to provide a patch to the cl-asdf port on FreeBSD, such as to ensure that the cl-asdf system on FreeBSD would have support for MKCL, along with some more of Common Lisp implementations that may already be available via FreeBSD ports

Any advice would be welcomed. Cheers

threads.d:1367:23: warning: implicit declaration of function 'MK_GC_get_stack_base' is invalid in C99 [-Wimplicit-function-declaration]
	if (MK_GC_SUCCESS != MK_GC_get_stack_base(&sb))
			     ^
threads.d:1371:10: warning: implicit declaration of function 'MK_GC_register_my_thread' is invalid in C99 [-Wimplicit-function-declaration]
	switch (MK_GC_register_my_thread(&sb))
		^
threads.d:1406:26: warning: implicit declaration of function 'MK_GC_unregister_my_thread' is invalid in C99 [-Wimplicit-function-declaration]
    MKCL_GC_NO_INTR(env, MK_GC_unregister_my_thread());
			 ^
../mkcl/external.h:2317:30: note: expanded from macro 'MKCL_GC_NO_INTR'
    MKCL_REALLY_NO_INTR(env, expr);			\
			     ^
../mkcl/external.h:2284:6: note: expanded from macro 'MKCL_REALLY_NO_INTR'
    (expr);					 \
     ^
threads.d:1519:31: warning: implicit declaration of function 'MK_GC_invoke_finalizers' is invalid in C99 [-Wimplicit-function-declaration]
	MKCL_GC_NO_INTR(env, count = MK_GC_invoke_finalizers()); /* returns the number of finalizers that were run, if we care... */
				     ^
../mkcl/external.h:2317:30: note: expanded from macro 'MKCL_GC_NO_INTR'
    MKCL_REALLY_NO_INTR(env, expr);			\
			     ^
../mkcl/external.h:2284:6: note: expanded from macro 'MKCL_REALLY_NO_INTR'
    (expr);					 \
     ^
threads.d:1632:3: error: unknown type name 'MK_GC_finalizer_notifier_proc'; did you mean 'GC_finalizer_notifier_proc'?
  MK_GC_finalizer_notifier_proc old_notifier;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  GC_finalizer_notifier_proc
/usr/local/include/gc/gc.h:181:29: note: 'GC_finalizer_notifier_proc' declared here
typedef void (GC_CALLBACK * GC_finalizer_notifier_proc)(void);
			    ^
threads.d:1634:39: warning: implicit declaration of function 'MK_GC_get_finalizer_notifier' is invalid in C99 [-Wimplicit-function-declaration]
  MKCL_GC_NO_INTR(env, old_notifier = MK_GC_get_finalizer_notifier());
				      ^
../mkcl/external.h:2317:30: note: expanded from macro 'MKCL_GC_NO_INTR'
    MKCL_REALLY_NO_INTR(env, expr);			\
			     ^
../mkcl/external.h:2284:6: note: expanded from macro 'MKCL_REALLY_NO_INTR'
    (expr);					 \
     ^
threads.d:1634:37: warning: incompatible integer to pointer conversion assigning to 'GC_finalizer_notifier_proc' (aka 'void (*)(void)') from 'int' [-Wint-conversion]
  MKCL_GC_NO_INTR(env, old_notifier = MK_GC_get_finalizer_notifier());
				    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../mkcl/external.h:2317:30: note: expanded from macro 'MKCL_GC_NO_INTR'
    MKCL_REALLY_NO_INTR(env, expr);			\
			     ^
../mkcl/external.h:2284:6: note: expanded from macro 'MKCL_REALLY_NO_INTR'
    (expr);					 \
     ^
threads.d:1636:24: warning: implicit declaration of function 'MK_GC_set_finalizer_notifier' is invalid in C99 [-Wimplicit-function-declaration]
  MKCL_GC_NO_INTR(env, MK_GC_set_finalizer_notifier(/*(MK_GC_finalizer_notifier_proc)*/ request_finalization));
		       ^
../mkcl/external.h:2317:30: note: expanded from macro 'MKCL_GC_NO_INTR'
    MKCL_REALLY_NO_INTR(env, expr);			\
			     ^
../mkcl/external.h:2284:6: note: expanded from macro 'MKCL_REALLY_NO_INTR'
    (expr);					 \
     ^
7 warnings and 3 errors generated.
gmake[2]: *** [GNUmakefile:81: threads.o] Error 1
gmake[2]: Leaving directory '/usr/local/src/mkcl-impl/mkcl-src/src/c'
gmake[1]: *** [Makefile:312: mkclmin.a] Error 2
gmake[1]: Leaving directory '/usr/local/src/mkcl-impl/mkcl-src/src'
gmake: *** [Makefile:86: all] Error 2

[patch_1.diff.txt](https://github.com/jcbeaudoin/MKCL/files/389397/patch_1.diff.txt)
[build.script.txt](https://github.com/jcbeaudoin/MKCL/files/389400/build.script.txt)

**Comment by jcbeaudoin** [comment]
Hello Sean,

On Thu, Jul 28, 2016 at 5:29 PM, Sean Champ <notifications@github.com>
wrote:

> Hello,
>
> Observing the support for MKCL in CL+J, and having taking up an interest
> about applying SWIG for C++ FFI in Common Lisp - specifically with LLVM on
> FreeBSD - moreover, towards ensuring a broader support for Common Lisp on
> FreeBSD, I've begun tinkering with developing a port for MKCL to FreeBSD.
> I've attached a preliminary diff of what I've been able to hack out for the
> port, so far.
>
> I believe that my patch may need some cleanups -- for instance, I would
> like to make sure I've not missed any __linux declarations in the source
> tree, such that could be accompanied with defined(BSD) compatibly.
> Furthermore, I'm not altogether certain if the patched source tree may be
> compatible with the project's style guidelines. In all candor, I've not
> been a lot of comfortable with C or C++ but I understand that there may a
> manner of a normative language model to each, in any respective edition of
> the C or C++ languages.
>
> Concerning the following patch, it does not go to much further of a
> semantic depth than preprocessor directives.
>
> Presently, I'm hoping that there may be any advice available as to how to
> address the following errors form the compiler.
>
> This is produced with the LLVM toolchain, more specifically the clang C
> compiler and the LLVM C++ compiler, on FreeBSD 10.3 amd64. I've attached a
> transcript of the entire build session, along with the patch.
>
> If it may be possible to build MKCL successfully on FreeBSD, I believe
> that there may be a good time to provide a patch to the cl-asdf port on
> FreeBSD, such as to ensure that the cl-asdf system on FreeBSD would have
> support for MKCL, along with some more of Common Lisp implementations that
> may already be available via FreeBSD ports
>
> Any advice would be welcomed. Cheers
>
>
>
This looks like a very interesting endeavor you have undertaken here. Thank
you for your efforts.

I have to admit that you are catching me a bit off guard here.  For a good
while I have been somewhat far away from OS API/threads issues and their
portability concerns as I am heavily reorganizing the
initialization/bootstrap code of MKCL. I will need a little while (a few
hours I hope) to get back into the proper mindset to address all you just
sent my way.

So please bear with me for a little while and I will get back to you with
what I hope will be useful comments, not too long from now.
The lineup you are using (a unix variant, here FreeBSD, with clang) is
definitely something that MKCL should support if it was not for my lack of
access to such a setup (btw I did a few attempts with clang on Linux
lately).

Cheers,

Jean-Claude Beaudoin

**Comment by spchamp** [comment]
Mr. Beaudoin,

If it may serve to be of any information with regards to the FreeBSD OS, there is a FreeBSD distribution available in a VMDK virtual image format, for 64 bit and 32 bit architecture emulation[1] Certainly the VMDK image could be applied as with any conventional kind of a machine virtualization application such as QEMU[2], VirtualBox[3], or any more kernel-oriented virtualization platforms such as Xen and Bhyve.  

With regards to documentation as in any manner of a "HOWTO" quality about FreeBSD applications, of course there is a complete FreeBSD Handbook available[4] as published  by the FreeBSD Foundation -- published, moreover, in multiple translations[5]. 

Personally, I believe LLVM is fairly well integrated with the FreeBSD platform. It's a part of the "base system" build, for instance - essentially, there as a kind of a baseline OS userspace component as may be built and installed normally beside the FreeBSD kernel itself. Of course, there's also a FreeBSD port for LLVM in each of its 3.7 and 3.8 minor versions. 

Personally, I believe that a FreeBSD OS can seem like a moderately complex sort of thing to describe. I'm afraid it may no seem as immediately user-friendly as, for instance, a Debian GNU Linux distribution.  After a certain effort in refining the generic baseline OS, I believe it can be applied as a very efficient OS environment -  whether as a stand-alone OS  with optional virtualization services, or in a conventional dual boot environment.

Personally, I don't believe as if FreeBSD may stocked with any kinds of, so to speak, "Gotchas." 

In some of an immediate search about the C API so far as may be applied for thread signaling on a Linux platform, as though correspondingly, I'd found a few resources about a Native POSIX Thread Library (NPLT) threading model on Linux. Candidly, I don't know if threading is addressed quite the same on FreeBSD. 

There are a few books about the design and the implementation of the FreeBSD kernel, at various releases of the FreeBD OS - wtih various editions of the same book, including a free edition[6] and two commercially published editions. Perhaps that may seem to be in venturing too far from the practical matter of application porting. As with regards to threads and signals, I believe that the folks who designed the FreeBSD kernel  have described the rationale and the model of it to quite a depth -- such as including the POSIX API features of the  model, and a manner of an overall rationale of the design. Though perhaps the design and implementation book may not inasmuch serve to address the nature of LLVM, juxtaposed to GCC, but threads - i think so...

[1] https://www.freebsd.org/where.html
[2] http://wiki.qemu.org/Main_Page
[3] http://virtualbox.org/
[4] https://www.freebsd.org/doc/handbook/
[5] https://docs.freebsd.org/doc/10.3-RELEASE/usr/local/share/doc/freebsd/
[6] https://www.freebsd.org/doc/en_US.ISO8859-1/books/design-44bsd/book.html

**Comment by jcbeaudoin** [comment]
Thanks to your good information I now have my own instance of FreeBSD
running under VirtualBox on my main development machine. This way I will be
able to more properly understand the modifications you needed to make.
(Currently working on that.)

BTW, I saw in the file build.script.txt you sent me the following "warning"
during the configuration of the Boehm GC:

configure: WARNING: "FreeBSD does not yet fully support threads with Boehm
GC."

That is cause for some concern I think.  Could this be an issue that has
been fixed in a more recent version of Boehm GC? MKCL trails somewhat
behind the latest GC version, it is at 7.4.0 instead of the more current
7.4.4.

**Comment by jcbeaudoin** [comment]
The latest 4 commits address items that you encountered during your port effort but that should not be FreeBSD specific. Please give them a look (or a "git pull" maybe).

I am still puzzled by the Boehm GC situation. There seems to be more than one "ports" of that GC to FreeBSD, one base one and a "threaded" one. I suspect that the "threaded" one has not been merged with the main Boehm GC branch yet.  But I would need to read the exact and complete source code of that "threaded" port version to be sure. How does one get to that?

**Comment by jcbeaudoin** [comment]
Hello Sean,

Sorry for this late reply but it took me all that time to be finally in a position to give a serious answer to your original question.  Now that I have cleared most of the confusion around the FreeBSD port (see the commits of the last few days up to until today 2016/08/17) I can tell you that yes MK_GC_finalizer_notifier_proc was indeed the precise type intentionally meant.

It is your unfortunate modification of MKCL/src/mkcl/mkcl-gc.h that led you down the wrong path such that instead of referencing the MKCL private version of the Boehm GC you ended up using a system wide version of the Boehm GC located in /usr/local and not modified for MKCL needs.  Your transcript of the compilation error messages contains this element:

/usr/local/include/gc/gc.h:181:29

which clearly points to that system wide version of the GC.

The bug that you tried to work around with your mkcl-gc.h modification was better handled by changing properly the CFLAGS variable in the MKCL/src/c/Makefile.in file.

That said, it was just one of the points that had to be addressed to port MKCL to FreeBSD.  The latest commits document the others (mostly tool quirks and signal handling map adjustment).

There is the remaining concern of that warning during Boehm GC configuration. It requires further investigation but as of right now it strongly gives the impression that the said warning is in fact a (forgotten?) left over from a previous period that ended a while ago without the warning being removed. For what I can tell up to now the GC seems to be working OK.

Therefore I think I can now declare the port of MKCL to FreeBSD as done. And MKCL should now be able to do normal service on FreeBSD. But let's consider it somewhat "alpha" until some more testing and usage happen...

Cheers,

JCB
