### ISSUE TITLE
declare ignorable has no effect in defmacro?

### ISSUE THREAD

**Issue by pipping** [jcbeaudoin/MKCL#7]
Please consider the following piece of code:
```common-lisp
(defmacro f (a b)
  b)

(defun g ()
  (format t "This is what we found: ~a~%" (f 'defined 'not-defined)))

(g)
```
Running it should print "This is what we found: NOT-DEFINED". Compiling it will typically yield a warning about how `a` is never used. If I go back and replace my original code with
```common-lisp
(defmacro f (a b)
  (declare (ignorable a b)) ;; this is new!
  b)

(defun g ()
  (format t "This is what we found: ~a~%" (f 'defined 'not-defined)))

(g)
```
then the warning should disappear. And it does (I've check this with CMU CL, ECL, SBCL, and others)... but not on MKCL. On MKCL, I continue to get the same warning. Sure enough, it disappears if I use `(declare (ignore a))` instead, leaving me with
```common-lisp
(defmacro f (a b)
  (declare (ignorable a b))
  #+mkcl (declare (ignore a)) ;; new now!
  b)

(defun g ()
  (format t "This is what we found: ~a~%" (f 'defined 'not-defined)))

(g)
```
which is the portable version that doesn't generate a warning. This looks like a bug to me, though

**Comment by jcbeaudoin** [comment]
It is a bug.

In fact this bug has already been fixed in what will become MKCL 1.2.0 but that version is still a work in progress and I have not made it publicly available yet.  And I have not yet back ported the fix to 1.1.X.
I will hunt the fix down and back port it shortly...

Thanks.

**Comment by jcbeaudoin** [comment]
The fix is now at the top of the master branch. Please give it a try.

**Comment by pipping** [comment]
I can confirm that 8045b9eb4e7fdb40cb9cea8ad257a9ea4ac75793 fixes the issue.
