### ISSUE TITLE
Feature request: Read syntax for unicode characters

### ISSUE THREAD

**Issue by pipping** [jcbeaudoin/MKCL#8]
The snippet

``` common-lisp
(format nil "~a" #\LATIN_SMALL_LETTER_L_WITH_STROKE)
```

works as expected(*) with
- acl 10.0
- ccl 1.11
- clisp 2.49
- cmucl 21a
- ecl 16.1.2
- sbcl 1.3.8

It currently does not work (for me) with abcl/lispworks/mkcl, even though mkcl defines `:unicode`. It would be nice if it did.

(*) with cmucl you need to surround the expression with `(ext:string-encode ... :utf-8)` to get it to print what one would expect.

**Comment by jcbeaudoin** [comment]
Right now you could always name #\LATIN_SMALL_LETTER_L_WITH_STROKE by its other name of #\u0142 instead, but I agree that it is not as convenient.

Maybe some optional module could be implemented to support this with some flexibility if enough internal hooks are provided to make it possible.  I will investigate...

**Comment by pipping** [comment]
Right, `#\latin_small_letter_l_with_stroke` would be a shorthand for `(name-char "latin_small_letter_l_with_stroke")` whereas `#\u0142` is a shorthand for `(code-char #x0142)`. The latter syntax is supported on 
* abcl 1.3.3
* ccl 1.11
* clisp 2.49
* ecl 16.1.2
* mkcl 1.1.9
* sbcl 1.3.8
acl/cmucl/lispworks btw.

This feature request should not so much be about the exact syntax (this being lisp, new syntax can always be invented), it's rather about the lookup functionality behind it.

So I'd like to be able to say at least
```
(format nil "~a" (name-char "latin_small_letter_l_with_stroke"))
```
This works with
* acl 10.0
* ccl 1.11
* clisp 2.49
* cmucl 21a
* ecl 16.1.2
* sbcl 1.3.8

but not currently abcl/lispworks/mkcl.

**Comment by pipping** [comment]
I've now put together [a short overview](https://gitlab.common-lisp.net/epipping/asdf/wikis/Unicode%20support%20overview#specifying-unicode-characters-by-name-or-number) of what syntax is supported by which lisp.

**Comment by jcbeaudoin** [comment]
commit ea8ef56f772a03aeed05ae48a3668feeeeb6f3d6 should make the code in the original post work as hoped provided that `(require :unicode-names)` is executed at some point before.
@pipping are you ok with this?

**Comment by pipping** [comment]
I can confirm that after loading `:unicode-names`, the following now all work:
```
#\latin_small_letter_l_with_stroke
#\u+0142
#\u0142
```

I cannot comment on whether loading `:unicode-names` for that purpose should be necessary or not (that's a design choice that's entirely up to you); the feature certainly works, thank you!
