### ISSUE TITLE
Allow the cmp system to be found

### ISSUE THREAD

**Issue by pipping** [jcbeaudoin/MKCL#9]
With a current installation of MKCL, what one has is:
- a cmp.a in sys, along with a functional cmp.asd
- a cmp.asd in sys:contrib, which is broken, though, in that it refers to a cmp.a in the same directory, which does not exist.

Since cmp.asd in sys:contrib is broken, something should be changed here. I'll try to lay out a few paths that I've considered.

A search in asdf for the cmp system in the order
- first sys:contrib
- then sys

will first find a broken asd file and lead to all kinds of errors.

Moreover, a search that only looks in sys:contrib will never find the correct system. Since sys: is not part of the source registry, such a search is typical.

This suggests that
- either cmp.asd in sys:contrib.asd could refer to ../cmp.a if cmp.a should continue to live in sys for some reason.
- or cmp.asd and cmp.a could be moved from sys to sys:contrib
- or cmp.asd from sys:contrib could be removed if sys was added to the source registry or
- something else that I haven't thought of

could be done in order to make handling of the cmp system from within ASDF easier.

(this is connected to https://gitlab.common-lisp.net/asdf/asdf/merge_requests/11)

**Comment by jcbeaudoin** [comment]
cmp.asd was never meant to exist in sys:contrib. The really intended copy of it is the one in sys:.
The one in sys:contrib is an inadvertent mistake and will be removed by the upcoming fix.

Thanks to you Elias for mentioning raising this issue here and to Daniel for describing it also
on the asdf-devel mailing list a bit earlier.

**Comment by jcbeaudoin** [comment]
This issue should now be fixed by this [commit 0ab1d53](https://github.com/jcbeaudoin/MKCL/commit/0ab1d537e09d9bc7aece2f5a3b90693580cbaebc).

**Comment by pipping** [comment]
Great, thanks. contrib/cmp.* is now gone. I checked with asdf 3.1.7.11 that this would not have broken anything. Things with 3.1.7.17 are more difficult but I'm confident those issues will be sorted out soon.

**Comment by pipping** [comment]
It seems not all is good just yet. There are still two test failures in ASDF 3.1.7.18 which have the same origin:

As Faré pointed out, the sole cmp.asd that is now installed (quoting here)
> [..] defines a system "cmp/cmp" having a component of type 'bundle with
path "cmp/cmp" instead of a system "cmp" having a component of type
:compiled-file with path "cmp" and pathname #p"SYS:CMP.FASB" or
something [..]

That doesn't seem right.

**Comment by fare** [comment]
@jcbeaudoin ALSO, please confirm whether or not ASDF should change its default source-registry to point at #p"SYS:" rather than #p"CONTRIB:" as the root tree for MKCL-specific .asd's.

**Comment by jcbeaudoin** [comment]
Now, this issue should really and finally be fixed by this new [commit 1e72d5d](https://github.com/jcbeaudoin/MKCL/commit/1e72d5d71f42041bd37fd419b0653b3cf6a1c87c)

With it a valid cmp.asd sits in sys: solely and all other bundled contribs are in sys:contrib.

**Comment by pipping** [comment]
Once https://gitlab.common-lisp.net/asdf/asdf/merge_requests/21 is merged, asdf will have no test failures when running on mkcl anymore (tested on linux).
